on:
  schedule:
#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#            │ │ │ │ │
#            │ │ │ │ │
#            │ │ │ │ │
    - cron: '0/10 * * * *'
      # ^ this means 9:00 AM every thursday
      # I can’t figure out the right syntax
      # for ‘every other thursday’

jobs:
  bump-cbmc-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get new CBMC version number
        run: |
          NEW_CBMC_VERSION=$(grep '^CBMC_VERSION =' src/config.inc | cut -d = -f 2 | scripts/increment_version.sh)
          echo ::set-env name=CBMC_VERSION::$NEW_CBMC_VERSION
          echo ::set-output name=CBMC_VERSION::$NEW_CBMC_VERSION
      - name: Update CBMC version
        run: |
          sed -i "s/CBMC_VERSION = .*/CBMC_VERSION = $CBMC_VERSION/" src/config.inc
      - name: Set git identity to github bot
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
      - name: Commit changes
        run: |
          git commit -a -m "Bump version to $CBMC_VERSION"
      - name: Push changes
        run: |
          git push
  perform-release:
    needs: bump-cbmc-version
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cbmc-${{needs.bump-cbmc-version.outputs.CBMC_VERSION}}
          release_name: cbmc-${{needs.bump-cbmc-version.outputs.CBMC_VERSION}}
          draft: false
          prerelease: true
