# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu-18_04:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Fetch dependencies
      run: sudo apt install g++ cmake ninja-build
    - name: Build using CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja
        ninja
    - name: Run CTest
      run: cd build; ctest -V .
  build-macos-10_15:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Fetch dependencies
      run: brew install cmake ninja
    - name: Build using CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja
        ninja
    - name: Run CTest
      run: cd build; ctest -V .
    
